export enum Sintomas {
  Febre = "Febre",
  DorDeCabeca = "Dor de cabeça",
  DorAbdominal = "Dor abdominal",
  Nauseas = "Náuseas",
  Vomitos = "Vômitos",
  DorNasCostas = "Dor nas costas",
  DorAtrasDosOlhos = "Dor atrás dos olhos",
  Tosse = "Tosse",
  DorNoPeito = "Dor no peito",
  FaltaDeAr = "Falta de ar",
  Fadiga = "Fadiga",
  TonturaVertigem = "Tontura e/ou vertigem",
  DificuldadeParaDormir = "Dificuldade para dormir",
  Inchaco = "Inchaço (edemas)",
  IrritacaoNaGarganta = "Irritação na garganta",
  ProblemasDeCoordenacao = "Problemas de coordenação",
  Diarreia = "Diarreia",
  Constipacao = "Constipação (intestino preso)",
  DorNasArticulacoes = "Dor nas articulações (dor nas juntas)",
  DoresMusculares = "Dores musculares",
  HemorragiaNasal = "Hemorragia nasal",
  PerdaDeMemoria = "Perda de memória",
  Desmaio = "Desmaio",
  Tremores = "Tremores",
  DorDeGarganta = "Dor de garganta",
  CongestaoNasal = "Congestão nasal e/ou coriza",
  DorDeOuvido = "Dor de ouvido",
  PerdaDoOlfato = "Perda do olfato",
  VermelhidaoOcular = "Vermelhidão ocular (olhos vermelhos)",
  DorOcular = "Dor ocular (dor na superfície dos olhos)",
  OlhosSalientes = "Olhos salientes (olhos saltados)",
  AlteracoesDeComportamento = "Alterações de comportamento",
  DorEscrotal = "Dor escrotal",
  DorOuQueimacaoAoUrinar = "Dor ou queimação ao urinar",
  NodulosNaMama = "Nódulos na mama (caroço no peito)",
  SecrecaoVaginal = "Secreção vaginal",
  CarocoNoPescoco = "Caroço no pescoço",
  PerdaDeCabelos = "Perda de cabelos/pelos",
  PontosVermelhosNaPele = "Pontos vermelhos na pele",
  SangramentoNaPele = "Sangramento na pele espontâneo",
  Taquicardia = "Taquicardia (aumento da frequência cardíaca)",
  PressaoBaixa = "Pressão baixa",
  BaixaProducaoDeUrina = "Baixa produção de urina (oligúria)",
  SudoreseExcessiva = "Sudorese excessiva",
  PeleAmarelada = "Pele amarelada",
  Coceira = "Coceira",
  PerdaDeApetite = "Perda de apetite",
  DorNasPanturrilhas = "Dor nas panturrilhas",
  SensibilidadeALuz = "Sensibilidade à luz",
  ArroxeamentoDaPele = "Arroxeamento da pele",
  VisaoEmbacada = "Visão embaçada"
}

export const DENGUE = {
  SYMPTOMS: [
    "febre (2 a 7 dias)",
    "febre alta (39º a 40ºC)",
    "dor de cabeça",
    "dor atrás dos olhos",
    "dores musculares",
    "dores articulares",
    "fraqueza",
  ],
  ALARM_SIGNS: [
    "dor abdominal intensa e contínua",
    "vômitos persistentes",
    "acúmulo de líquidos em cavidades corporais",
    "hipotensão postural",
    "lipotimia",
    "sangramento de mucosa",
    "letargia",
    "irritabilidade",
    "aumento progressivo do hematócrito",
    "aumento do tamanho do fígado",
  ],
  SHOCK_SIGNS: [
    "taquicardia",
    "extremidades distais frias",
  ]
}

export const UNITS = {
  UBS: "Unidade Básica de Saúde",
  UPA: "Unidade de Pronto Atendimento",
}

export const GROUP_ATTENDANCE = {
  GROUP_A: UNITS.UBS,
  GROUP_B: UNITS.UPA + "/" + UNITS.UBS,
  GROUP_C: UNITS.UPA,
  GROUP_D: UNITS.UPA,
}

export const COMORBIDITIES = [
  "Diabetes",
  "Hipertensão arterial",
  "Doenças cardíacas",
  "Doenças pulmonares crônicas",
  "Obesidade",
  "Doenças autoimunes",
  "Doenças neurológicas crônicas",
  "Doenças alérgicas",
  "Doenças renais crônicas",
  "Pneumopatias crônicas graves",
  "Hemoglobinopatias graves",
  "Doença ácido péptica",
  "Hepatopatias crônicas",
];

export const RISK_GROUPS = [
  "Lactente",
  "Gestante",
  "Pessoa com Transtorno do Espectro Autista",
  "Adulto com mais de 60 anos",
  "Fumante",
  "Criança com menos de 5 anos",
  "Pessoa que realiza tratamento de imurossupressão",
  "Pessoa no período pós-parto",
];