services:
  app:
    restart: on-failure
    build: .
    depends_on:
      - postgres
    environment:
      NODE_ENV: development
      POSTGRES_HOST: postgres
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      ENVIRONMENT_TYPE: PRODUCTION
      PORT: 3000
    ports:
      - "81:3333"
      - "443:3333"
    volumes:
      - .:/app/
      - /app/node_modules
      # - /etc/letsencrypt/live/monipaep.icmc.usp.br:/etc/ssl/certs:ro

  postgres:
    image: postgres:11
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - /home/monipaep/IC-MoniPaEp-Backend/postgres_volume/:/var/lib/postgresql/data/

  pgweb:
    image: sosedoff/pgweb
    restart: on-failure
    ports:
      - "8081:8081"
    environment:
      PGWEB_DATABASE_URL: ${PGWEB_DATABASE_URL}
    depends_on:
      - postgres
