services:
  app:
    restart: always
    build: 
      context: .
      network: host
    depends_on:
      - postgres
    environment:
      NODE_ENV: development
      POSTGRES_HOST: postgres
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      ENVIRONMENT_TYPE: DEVELOPMENT
      PORT: 3333
    ports:
      - "3333:3333"
    volumes:
      - .:/app
      - /app/node_modules

  postgres:
    image: postgres:11-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgweb:
    image: sosedoff/pgweb
    restart: on-failure
    ports:
      - "8081:8081"
    environment:
      PGWEB_DATABASE_URL: ${PGWEB_DATABASE_URL}
    depends_on:
      - postgres

volumes:
  postgres-data:
