# ---- Base Stage ----
FROM node:23.14-alpine AS base
WORKDIR /app
COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile --production

# ---- Build Stage ----
FROM node:23.14-alpine AS build
WORKDIR /app
COPY --from=base /app/node_modules ./node_modules
COPY . .
RUN yarn build

# ---- Final Stage ----
FROM node:23.14-alpine AS prod
WORKDIR /app
COPY --from=build /app/dist ./dist
COPY --from=base /app/node_modules ./node_modules
COPY package.json ./
ENV NODE_ENV=production
EXPOSE 3333
CMD ["node", "dist/index.js"]
