services:
  monipaep-backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    env_file: .env
    volumes:
      - /etc/letsencrypt/archive/monipaep.icmc.usp.br:/etc/ssl/certs:ro
    network_mode: "host"
