name: Deploy to EC2

on:
  pull_request:
    branches:
      - main 
permissions:
      id-token: write
      contents: read 
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Code Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: File upload to S3 Bucket
        run: |
          aws s3 cp --recursive ./ ${{vars.AWS_S3_BUCKET}}

      - name: Connect to EC2 Instance
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" | ssh -o StrictHostKeyChecking=no -i /dev/stdin ${{ secrets.EC2_INSTANCE_USER }}@${{ secrets.EC2_PUBLIC_DNS }}

      - name: Get files from S3
        run: |
          cd monipaep-backend &&
          aws s3 cp --recursive ${{vars.AWS_S3_BUCKET}} ./

      - name: Config project and migrations
        run: |
          echo $(cat .env.example) >> .env &&
          docker-compose up -d &&
          npm run migration:run 
          