name: Deploy to EC2

on:
  pull_request:
    branches:
      - main 
permissions:
      id-token: write
      contents: read 
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Code Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: File upload to S3 Bucket
        run: |
          aws s3 cp --recursive ./ ${{vars.AWS_S3_BUCKET}}

      - name: Deploy on EC2
        env:
          AWS_S3_BUCKET: ${{ vars.AWS_S3_BUCKET }}
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > aws-key.pem
          chmod 600 aws-key.pem
          ssh -o StrictHostKeyChecking=no -i aws-key.pem ${{ secrets.EC2_INSTANCE_USER }}@${{ secrets.EC2_PUBLIC_DNS }} << 'EOF'
            # Download S3 Files
            cd monipaep-backend
            aws s3 cp --recursive $AWS_S3_BUCKET ./
            
            # Project config and migrations
            echo $(cat .env.example) >> .env
            docker-compose up -d
            npm run migration:run
          EOF
          rm aws-key.pem